# Generated by Django 5.0.2 on 2024-03-12 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Especialidad', models.CharField(max_length=100)),
                ('Doctor', models.TextField(blank=True)),
                ('Prueba', models.TextField(blank=True)),
                ('Calendario_de_disponibilidad', models.TextField(blank=True)),
                ('Nombre_del_paciente', models.TextField(max_length=100)),
                ('Cédula_del_paciente', models.IntegerField(blank=True)),
                ('Teléfono_de_contacto', models.IntegerField(blank=True)),
                ('Síntomas', models.TextField(max_length=100)),
                ('Información_relevante', models.TextField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
