# Generated by Django 5.0.2 on 2024-03-12 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='Prueba',
        ),
    ]
