# Generated by Django 5.0.2 on 2024-03-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_citas_prueba'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='Consultorio',
            field=models.IntegerField(null=True),
        ),
    ]
