# Generated by Django 5.0.2 on 2024-03-13 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_citas_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='Estado',
            field=models.TextField(blank=True),
        ),
    ]
