# Generated by Django 5.0.2 on 2024-03-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_citas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='Especialidad',
            field=models.CharField(max_length=24),
        ),
    ]
