# Generated by Django 5.0.2 on 2024-03-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_estadocita_alter_citas_calendario_de_disponibilidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(default='08:00:00')),
            ],
        ),
    ]
