# Generated by Django 5.0.2 on 2024-03-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_hora'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hora',
        ),
        migrations.AlterField(
            model_name='citas',
            name='Hora',
            field=models.TimeField(default='08:00:00'),
        ),
    ]
