# Generated by Django 5.0.2 on 2024-03-18 03:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_alter_citas_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='Hora',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
