# Generated by Django 5.0.2 on 2024-03-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_citas_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='Cédula_del_paciente',
            field=models.TextField(max_length=11),
        ),
        migrations.AlterField(
            model_name='citas',
            name='Teléfono_de_contacto',
            field=models.TextField(max_length=20),
        ),
    ]
