# Generated by Django 5.0.2 on 2024-03-18 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_citas_cédula_del_paciente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibilidadCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cupos_disponibles', models.PositiveIntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.doctor')),
            ],
        ),
    ]
