# Generated by Django 5.0.2 on 2024-03-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_remove_citas_user_perfilanalista_citas_analista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilpaciente',
            name='apellidos',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='direccion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='perfilpaciente',
            name='nombres',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
