# Generated by Django 5.0.2 on 2024-03-19 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_rename_perfilpaciente_perfilusuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilanalista',
            old_name='usuario',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='usuario',
            new_name='user',
        ),
    ]
