# Generated by Django 5.0.2 on 2024-03-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_alter_esp_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='direccion',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
