# Generated by Django 5.0.2 on 2024-03-24 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_alter_perfilusuario_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadcita',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.doctor'),
        ),
        migrations.DeleteModel(
            name='PerfilDoctor',
        ),
    ]
