# Generated by Django 5.0.2 on 2024-03-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_alter_disponibilidadcita_doctor_delete_perfildoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
