# Generated by Django 5.0.2 on 2024-03-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_alter_doctor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
