# Generated by Django 5.0.2 on 2024-03-27 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_alter_doctor_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citas',
            name='analista',
        ),
        migrations.AddField(
            model_name='citas',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadcita',
            name='consultorio',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='citas',
            name='Calendario_de_disponibilidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.disponibilidadcita'),
        ),
        migrations.AlterField(
            model_name='citas',
            name='Consultorio',
            field=models.CharField(default='1', max_length=3),
        ),
        migrations.AlterField(
            model_name='citas',
            name='Hora',
            field=models.CharField(default='08:00', max_length=3),
        ),
        migrations.AlterField(
            model_name='citas',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.TextField(max_length=11)),
                ('edad', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.perfilusuario')),
            ],
        ),
        migrations.AlterField(
            model_name='citas',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.paciente'),
        ),
    ]
