# Generated by Django 5.0.2 on 2024-03-27 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_remove_citas_analista_citas_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadcita',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.esp'),
        ),
    ]
