# Generated by Django 5.0.2 on 2024-04-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_disponibilidadcita_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='Consultorio',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='citas',
            name='Hora',
            field=models.CharField(max_length=3),
        ),
    ]
