# Generated by Django 5.0.2 on 2024-04-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_alter_citas_consultorio_alter_citas_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidadcita',
            name='fecha',
            field=models.CharField(max_length=12),
        ),
    ]
