# Generated by Django 5.0.2 on 2024-04-02 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_alter_disponibilidadcita_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='Hora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hora_cita', to='tasks.disponibilidadcita'),
        ),
    ]
