# Generated by Django 5.0.2 on 2024-04-03 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_alter_citas_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='fecha',
            field=models.CharField(default='01/01/2024', max_length=12),
        ),
    ]
