# Generated by Django 5.0.2 on 2024-04-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_citas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='Estado',
            field=models.TextField(default='Pendiente'),
        ),
        migrations.DeleteModel(
            name='EstadoCita',
        ),
    ]
