# Generated by Django 5.0.2 on 2024-04-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_alter_citas_estado_delete_estadocita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='Hora',
            field=models.CharField(max_length=10),
        ),
    ]
